/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.fuxi.ghostroot;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int output=0x7f060004;
        public static final int run=0x7f060001;
        public static final int scroll=0x7f060003;
        public static final int status=0x7f060002;
        public static final int subtitle=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        /**  以下为历史遗留（按钮已删除，字符串暂时保留以免 R.java 变动过大） 
         */
        public static final int btn_copy=0x7f040006;
        /**  主按钮 
         */
        public static final int btn_run=0x7f040001;
        public static final int btn_running=0x7f040002;
        public static final int btn_save=0x7f040007;
        /**  日志区 
         */
        public static final int log_hint=0x7f040004;
        public static final int log_tip=0x7f040005;
        /**  状态行 
         */
        public static final int status_idle=0x7f040003;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}
